import React from "react";

export const metadata = {
  title: "About Course App",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div>
      <h1 className="text-3xl">About Page</h1>
    </div>
  );
};

export default AboutPage;
